name: build

on:
  push:
    branches:
    tags:
    paths-ignore:
      - ".github/workflows/ci-v2.yml"
      - "v2/**"
  pull_request:
    paths-ignore:
      - ".github/workflows/ci-v2.yml"
      - "v2/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: disable and stop mono-xsp4.service (wtf?)
        run: |
          sudo systemctl stop mono-xsp4.service || true
          sudo systemctl disable mono-xsp4.service || true

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
        id: go

      - name: launch mongodb
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: "6.0"

      - name: checkout
        uses: actions/checkout@v4

      - name: build the example
        working-directory: _example
        run: |
          go build -race
        env:
          TZ: "America/Chicago"

      - name: build and test
        run: |
          go test -timeout=60s -v -race -p 1 -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
          go build -race
        env:
          TZ: "America/Chicago"
          ENABLE_MONGO_TESTS: "true"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: 1.61

      - name: submit coverage
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
